[tool.poetry]
name = "airflow-code-center"
version = "0.1.0"
description = ""
authors = ["yeangPan <yeangPan@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
pydantic = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
